/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"
#include "stm32f446xx_i2c_driver.h"

#define BME280_ADDR 0x76

//Register settings
#define REG_F5_ADDR         0xF5
#define REG_F4_ADDR         0xF4

//Config one sample every 1s
//Register 0xF5
//Set Bit 7:5 to b'101'
#define REG_F5_SET          (5 << 5)

//Config Power mode to Normal
//Set Bit 1:0 to b'11'
//Config over sampling of temperature data to highest resolution
//Register 0xF4
//Set Bit 7:5 to b'101'
#define REG_F4_SET          ( (5 << 5) | (3 << 0) )

//DIG Tx register addresses
#define DIG_T1				0x88
#define DIG_T2				0x8A
#define DIG_T3				0x8C

uint8_t setup_reg_data[] = {REG_F5_ADDR,
                            REG_F5_SET,
                            REG_F4_ADDR,
                            REG_F4_SET
                            };

I2C_Handle_t i2c_handle;

//Receive buffer
//uint8_t rcv_buf[32];
uint8_t rcv_buf[2];

void delay(void)
{
	//for(uint32_t i = 0; i < 500000/2; i++);
	//for(uint32_t i = 0; i < 500000; i++);
	for(uint32_t i = 0; i < 5000000; i++);

}

void i2c_gpio_init(void)
{
	GPIO_Handle_t i2c_pins;

	i2c_pins.pGPIOx								= GPIOB;
	i2c_pins.GPIO_PinConfig.GPIO_PinMode		= GPIO_MODE_ALTFN;
	i2c_pins.GPIO_PinConfig.GPIO_PinAltFunMode	= 4;
	i2c_pins.GPIO_PinConfig.GPIO_PinOPType		= GPIO_OP_TYPE_OD;
	i2c_pins.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_PIN_PU;
	i2c_pins.GPIO_PinConfig.GPIO_PinSpeed		= GPIO_SPEED_FAST;

	//SCL
	i2c_pins.GPIO_PinConfig.GPIO_PinNumber		= 6;

	GPIO_Init(&i2c_pins);

	//SDA
	i2c_pins.GPIO_PinConfig.GPIO_PinNumber		= 7;

	GPIO_Init(&i2c_pins);
}

void i2c1_init(void)
{
	i2c_handle.pI2Cx						= I2C1;
	i2c_handle.I2C_Config.I2C_ACKControl	= I2C_ACK_ENABLE;
	i2c_handle.I2C_Config.I2C_DeviceAddress	= BME280_ADDR;
	i2c_handle.I2C_Config.I2C_FMDutyCycle	= I2C_FM_DUTY_2;
	i2c_handle.I2C_Config.I2C_SCLSpeed		= I2C_SCL_SPEED_SM;

	I2C_Init(&i2c_handle);
}

int read_register_data(I2C_Handle_t *pI2CHandle, uint8_t *pTxbuffer, uint8_t *pRxBuffer, uint32_t Len)
{
	//Ping register to send data
	I2C_MasterSendData(pI2CHandle, pTxbuffer, 1, BME280_ADDR, I2C_ENABLE_SR);

	//Receive data from register
	I2C_MasterReceiveData(pI2CHandle, pRxBuffer, Len, BME280_ADDR, I2C_ENABLE_SR);

	if (Len > 1)
	{
		return ( (pRxBuffer[1] << 8) | pRxBuffer[0] );
	}
	else
	{
		return pRxBuffer[0];
	}

}

int get_temperature(uint32_t adc_t, uint16_t dig_t1, uint16_t dig_t2, uint16_t dig_t3)
{
	uint32_t var1, var2, t_fine;
	int temp_celcius, temp_farenheit;

	var1 = ( ( ( ( adc_t >> 3 ) - ( ( uint32_t ) dig_t1 << 1 ) ) ) * ( (uint32_t) dig_t2)) >> 11;
	var2 = ( ( ( ( ( adc_t >> 4 ) - ( ( uint32_t ) dig_t1) ) * (( adc_t >> 4) - ( (uint32_t) dig_t1 ))) >> 12) * ((uint32_t) dig_t3)) >> 14;

	t_fine = var1 + var2;

	//Temperature is in Celcius and is off by 100.
	temp_celcius = ( t_fine * 5 + 128) >> 8;
	temp_farenheit 	= ((temp_celcius * 9)/5) + 32 * 100;


	return temp_farenheit;
}

int main(void)
{
	printf("Starting application\n");

    //Initialize GPIO pins
	printf("Initialize GPIO pins\n");
	i2c_gpio_init();

	//Initialize I2C
	printf("Initialize and enableI2C\n");
	i2c1_init();

	//Enable I2C
	I2C_PeripheralControl(I2C1, ENABLE);

	//Enable ACK?
	//ACK bit is made 1 after PE=1
	I2C_ManageAcking(I2C1, I2C_ACK_ENABLE);


	//Configure registers
	printf("Configure registers\n");
	uint32_t array_length = sizeof(setup_reg_data);
	I2C_MasterSendData(&i2c_handle, setup_reg_data, array_length, BME280_ADDR, I2C_ENABLE_SR);

	//Get DIG T calibration data
	printf("Get calibration data\n");
	//int* reg_addr	= DIG_T1;
	uint8_t reg_addr	= 0x88;
	uint16_t dig_t1 = read_register_data(&i2c_handle, &reg_addr, rcv_buf, 2);
	printf("Data : %x\n", dig_t1);

	reg_addr	= 0x8A;
	uint16_t dig_t2 = read_register_data(&i2c_handle, &reg_addr, rcv_buf, 2);
	printf("Data : %x\n", dig_t2);

	reg_addr	= 0x8C;
	uint16_t dig_t3 = read_register_data(&i2c_handle, &reg_addr, rcv_buf, 2);
	printf("Data : %d\n", dig_t3);


	//Correct calibration values. Make variables unsigned to match dig_c1 output ?
	if (dig_t2 > 32767)
	{
		dig_t2 = dig_t2 - 65536;
	}

	if (dig_t3 > 32767)
	{
		dig_t3 = dig_t3 - 65536;
	}

	uint32_t raw_reg_temp;
	int temperature;

    /* Loop forever */
	while(1)
	{
		//Read temperature from register
		printf("Read temperature from register\n");
		reg_addr	= 0xfa;
		uint8_t d1 = read_register_data(&i2c_handle, &reg_addr, rcv_buf, 2);

		reg_addr	= 0xfb;
		uint8_t d2 = read_register_data(&i2c_handle, &reg_addr, rcv_buf, 2);

		reg_addr	= 0xfc;
		uint8_t d3 = read_register_data(&i2c_handle, &reg_addr, rcv_buf, 2);

		//d3[0:3] are not valid so adjustment is made
		raw_reg_temp = ( (d1 << 16) | (d2 << 8) | d3) >> 4;

		temperature = get_temperature(raw_reg_temp, dig_t1, dig_t2, dig_t3);

		printf("Temperature (F)= %d.%d\n", temperature / 100, temperature % 100);

		delay();

	}
}
